Traceback (most recent call last):
  File "c:/Users/Johnatan/Documents/Desenvolvimento/Python/Python-Automatizando-tarefas/10 - debugging/obtendo-traceback-como-uma-string.py", line 10, in <module>
    spam()
  File "c:/Users/Johnatan/Documents/Desenvolvimento/Python/Python-Automatizando-tarefas/10 - debugging/obtendo-traceback-como-uma-string.py", line 4, in spam
    bacon()
  File "c:/Users/Johnatan/Documents/Desenvolvimento/Python/Python-Automatizando-tarefas/10 - debugging/obtendo-traceback-como-uma-string.py", line 7, in bacon
    raise Exception('This is the error message.')
Exception: This is the error message.
